### ISSUE TITLE
can't run mongo sharding

### ISSUE THREAD

**Issue by nguyentanloc518091** [gjovanov/mongo-swarm#2]
when i run all the command "vagrant up". i get the error
.
4un39nr 2019-05-07T10:47:13.580+0000 I SHARDING [shard-registry-reload] Periodic reload of shard registry failed :: caused by :: NotYetInitialized: could not get updated shard list from config server :: caused by :: Cannot use non-local read concern until replica set is finished initializing.; will retry after 30s

**Comment by gjovanov** [comment]
@nguyentanloc518091 - as the process of setting up a ReplicaSet is an asynchrous one and it can take some to elect a primary, and in the meanwhile ansible tasks only start the process of deploying ReplicaSets, but it doesn't wait for the ReplicaSet primary to get elected, potentially it can happen that the command fails.

What you can do is manually run the commands:
```
ansible-playbook /vagrant/ansible/docker.yml -i /vagrant/ansible/hosts/cluster
ansible-playbook /vagrant/ansible/swarm.yml -i /vagrant/ansible/hosts/cluster
ansible-playbook /vagrant/ansible/mongo.yml -i /vagrant/ansible/hosts/cluster
```
on **cd**. `vagrant ssh cd`

Another thing that can happen is that you have corrupted config db left from previous starting of clusters. In that case you can start it with fresh config dbs.

**Comment by nguyentanloc518091** [comment]
i run vagrant ssh cd but get the error.

![image](https://user-images.githubusercontent.com/13232868/57615317-99afce00-75a5-11e9-8697-7496a6578347.png)

**Comment by duycuong87vn** [comment]
@nguyentanloc518091 , same problem with me,
as suggest from @gjovanov , you need to fresh all swarm-cluster again.
and now, it's ok for me.

**Comment by gjovanov** [comment]
As I mentioned in #1 and #3, there is new version with the demo app.

I will close this one. Let me know in case you have any issue with the new version.
